export const CALL_API_ACTION = "CALL_API_HTTP";
export const CALL_API_ACTION_FAIL = "CALL_API_ACTION_FAIL";

export const HTTP_POST = "POST";
export const HTTP_GET = "GET";

export const CONTENT_TYPE = {
    JSON : "application/json",
    XML  : "application/xml",
    TEXT : "text/plain",
    HTML : "text/html",
    STREAM : "application/octet-stream",
    FORM : "application/x-www-form-urlencoded",
    FORM_DATA : "multipart/form-data",
};

export const ERROR = {
    USER_NOT_LOGIN : "ERROR_USER_NOT_LOGIN",
}

//修改密码
export const API_CHANGEPWD = 'API_CHANGEPWD';

export const API_LOGIN = "API_LOGIN";
export const API_LOGOUT = "API_LOGOUT";
export const API_USER_INFO = "API_USER_INFO";
//轮播广告
export const API_BANNER_ADD = "API_BANNER_ADD";
export const API_BANNER_DEL = "API_BANNER_DEL";
export const API_BANNER_UPDATE = "API_BANNER_UPDATE";
export const API_BANNER_SELECT = "API_BANNER_SELECT";
//消息管理
export const API_MESSAGE_ADD = "API_MESSAGE_ADD";
export const API_MESSAGE_DEL = "API_MESSAGE_DEL";
export const API_MESSAGE_SELECT = "API_MESSAGE_SELECT";


//角色管理
export const API_ROLE_SELECT = "API_ROLE_SELECT";

export const API_ROLE_UPDATE = 'API_ROLE_UPDATE';
export const API_ROLE_DELETE = 'API_ROLE_DELETE';
export const API_ROLE_ADD ='API_ROLE_ADD';
export const API_ROLE_QX = 'API_ROLE_QX';



//人员管理
export const  API_USER_SELECT ='API_USER_SELECT';
export const    API_USER_ADD ='API_USER_ADD';
export const     API_USER_UPDATE ='API_USER_UPDATE';
export const     API_USER_DELETE = 'API_USER_DELETE';


//活动
export const  API_HUODONG_SELECT ='API_HUODONG_SELECT';
export const  API_HUODONG_UPD ='API_HUODONG_UPD';


//获取用户信息列表
export const  API_USER_INFO_LIST ='API_USER_INFO_LIST';
export const  API_USER_INFO_OUT ='API_USER_INFO_OUT';

// 售卖审核
export const  API_SHOUMAI_SHENHE_LIST ='API_SHOUMAI_SHENHE_LIST';
export const  API_SHOUMAI_SHENHE_COMMIT ='API_SHOUMAI_SHENHE_COMMIT';
export const  API_QISHUXINXI_G ='API_QISHUXINXI_G';
export const  API_ADD_QISHUXINXI_P ='API_ADD_QISHUXINXI_P';
//每日一句
export const API_MEIRIYIJU_LIST = "API_MEIRIYIJU_LIST";
export const API_UPDATE_QISHUXINXI_P = "API_UPDATE_QISHUXINXI_P";
export const API_MEIRIYIJU_ADD = "API_MEIRIYIJU_ADD";
export const API_MEIRIYIJU_DEL = "API_MEIRIYIJU_DEL";
export const API_MEIRIYIJU_EXAMPLE_DOWN = "API_MEIRIYIJU_EXAMPLE_DOWN";

export const API_GETALL_CLASS_G = "API_GETALL_CLASS_G";
export const API_TIJIAOSHENHE_G = "API_TIJIAOSHENHE_G";
export const API_SHENHE_G = "API_SHENHE_G";
// 课程列表
export const API_COURSE_ADD = "API_COURSE_ADD";
export const API_COURSE_SUBMITSHENHE = "API_COURSE_SUBMITSHENHE";
export const API_COURSE_DELSECTION = "API_COURSE_DELSECTION";
export const API_COURSE_SECTIONSTATE = "API_COURSE_SECTIONSTATE";
export const API_COURSE_GETLEVELCOURSE = "API_COURSE_GETLEVELCOURSE";
export const API_COURSE_GETSECTIONINFO = "API_COURSE_GETSECTIONINFO";
export const API_COURSE_GETSECTIONLIST = "API_COURSE_GETSECTIONLIST";
export const API_COURSE_UPDATESECTION = "API_COURSE_UPDATESECTION";
export const API_COURSE_LEVEL = "API_COURSE_LEVEL";
export const API_COURSE_LEVEL1 = "API_COURSE_LEVEL1";
export const API_COURSE_SHENHE = "API_COURSE_SHENHE";
export const API_LOG = "API_LOG";
// 财务系统-订单列表
export const API_FINANCIAL_LIST = "API_FINANCIAL_LIST";
export const API_FINANCIAL_PHASELIST = "API_FINANCIAL_PHASELIST";
// 修改课程名称
export const API_UPDATE_CLASSSNAME = "API_UPDATE_CLASSSNAME";
export const API_CONFIG = "API_CONFIG";
export const API_REFUND_LIST = "API_REFUND_LIST";

export const API_SHOUDONG_REFUND = "API_SHOUDONG_REFUND";

export const API_REFUND_SHENHE = "API_REFUND_SHENHE";
export const API_REFUND_COMMIT = "API_REFUND_COMMIT";
export const API_REFUND_SHENHE_COMMIT = "API_REFUND_SHENHE_COMMIT";
export const API_REFUND_SHENHE_CHAKAN = "API_REFUND_SHENHE_CHAKAN";
export const API_REFUND_R_COMMIT = "API_REFUND_R_COMMIT";
export const API_CAIWU_WATER = "API_CAIWU_WATER";

// 确认收人统计
export const API_EARNINGS = "API_EARNINGS";
// 售卖方式删除
export const API_SHOUMAI_DEL = "API_SHOUMAI_DEL";
export const API_RE_REFUND = "API_RE_REFUND";
export const API_PHASE_UP = "API_PHASE_UP";